# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Stage 1: Build
FROM node:lts-alpine AS build
WORKDIR /app

# Install dependencies and build
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
RUN npm ci && npm run build

# Stage 2: Runtime
FROM node:lts-alpine AS runtime
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install only production dependencies without running scripts
RUN npm ci --omit=dev --ignore-scripts

# Copy built files
COPY --from=build /app/dist ./dist

# Default command
CMD ["node", "dist/index.js"]
