name: 3. Publish Package

on:
  workflow_dispatch:

jobs:
  validation:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    steps:
      - name: Extract version from tag
        id: extract_version
        run: |
          echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ steps.extract_version.outputs.version }}

      - name: Validate Version
        run: |
          if [ ! -f "changelog/${{ steps.extract_version.outputs.version }}.md" ]; then
            echo "Changelog file for ${{ steps.extract_version.outputs.version }} not found"
            exit 1
          fi
          echo "Changelog validation successful"

          version=v$(node -p "require('./package.json').version")

          if [ "$version" != "${{ steps.extract_version.outputs.version }}" ]; then
            echo "Version mismatch: $version != ${{ steps.extract_version.outputs.version }}"
            exit 1
          fi
          echo "Version validation successful"

  publish-npm:
    needs: validation
    runs-on: ubuntu-latest
    outputs:
      version: ${{ needs.validation.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ needs.validation.outputs.version }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install and Build
        run: |
          npm install

          chmod +x ./dist/index.js

      - name: Publish package
        run: |
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          npm publish --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  create-release:
    needs: [publish-npm]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ needs.publish-npm.outputs.version }}

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.publish-npm.outputs.version }}
          bodyFile: "changelog/${{ needs.publish-npm.outputs.version }}.md"
