name: Publish Package

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag version'
        required: true
        type: string

jobs:
  validate-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate changelog
        id: validate-changelog
        run: |
          if [ ! -f "changelog/${{ github.event.inputs.tag }}.md" ]; then
            echo "Changelog file for ${{ github.event.inputs.tag }} not found"
            exit 1
          fi
          echo "Changelog validation successful"

  publish-npm:
    needs: validate-changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Publish package
        run: |
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          npm publish --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  create-release:
    needs: publish-npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read changelog
        id: changelog
        run: |
          echo "content<<EOF" >> $GITHUB_OUTPUT
          cat changelog/${{ github.event.inputs.tag }}.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: Release ${{ github.event.inputs.tag }}
          body: |
            ${{ steps.changelog.outputs.content }}
          draft: false
          prerelease: false
