name: Release Versioning
on:
  # push:
  #   branches:
  #     - 'feature/**'
  #     - 'develop/**'
  #     - 'hotfix/**'
  #     - 'support/**'
  #     - 'release/**'
  pull_request:
    branches:
      - main
      - 'feature/**'
      - 'develop/**'
      - 'hotfix/**'
      - 'support/**'
      - 'release/**'

jobs:
  semver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: semver-tag
        uses: gandarez/semver-action@master
        with:
          branching_model: "git-flow"

      - name: 🔖 Create Git Tag
        uses: rickstaa/action-create-tag@v1.7.2
        with:
          tag: ${{ steps.semver-tag.outputs.semver_tag }}
      
      - name: "Created tag"
        run: echo "tag ${{ steps.semver-tag.outputs.semver_tag }}"