name: Release Versioning
on:
  # push:
  #   branches:
  #     - 'feature/**'
  #     - 'develop/**'
  #     - 'hotfix/**'
  #     - 'support/**'
  #     - 'release/**'
  pull_request:
    branches:
      - main
      - 'feature/**'
      - 'develop/**'
      - 'hotfix/**'
      - 'support/**'
      - 'release/**'

jobs:
  semver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Application Version
        id: version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          enable_prerelease_mode: true
        
      # - name: 🔖 Create Git Tag
      #   uses: rickstaa/action-create-tag@v1.7.2
      #   with:
      #     tag: ${{ steps.version.outputs.version }}
      
      - name: "Created tag"
        run: echo "tag ${{ steps.version.outputs.version_tag }}"