name: Semantic Versioning
on:
  push:
    branches:
      - main
      - develop

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: semver
        uses: gandarez/semver-action@v2.0.0
        with:
          branching_model: "git-flow"
          main_branch_name: "main"
          develop_branch_name: "develop"
      
      - name: Push tag to origin
        run: git push origin ${{ steps.semver.outputs.semver_tag }}
